title 0.4

note over browser:
browser executes html-code
end note

browser->+server: HTTP POST https://studies.cs.helsinki.fi/exampleapp/spa
server-->-browser: response 302

browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/notes
server-->browser: HTML-coder->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
server-->browser: main.css
browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.js
server-->browser: main.js

note over browser:
browser starts executing js-code
that requests JSON data from server 
end note

browser->server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
server-->browser: [{ content: "Hello there", date: "2021-08-12" }, ...]

note over browser:
browser executes the event handler
that renders notes to display
end note